POST http://localhost:13000/user/update-location
content-type: application/json
Authorization: Bearer demo-taker-1

{
  "location": {
    "lat": "41.082185",
    "lng": "29.027520"
  }
}

GET http://localhost:13000/user/get
content-type: application/json
Authorization: Bearer demo-taker-1


POST http://localhost:13000/maker/save-settings
content-type: application/json
Authorization: Bearer demo-taker-1

{
  "minAmount": 100,
  "maxAmount": 1000,
  "range": 10
}

POST http://localhost:13000/maker/toggle-online
content-type: application/json
Authorization: Bearer demo-taker-1

{
  "online": true
}

POST http://localhost:13000/maker/confirm-withdrawal
content-type: application/json
Authorization: Bearer demo-maker-1

{
  "isApproved": true,
  "withdrawalId": "5a885ee39409ca0422a3acc2"
}

POST http://localhost:13000/taker/create-withdrawal
content-type: application/json
Authorization: Bearer demo-taker-1

{
  "amount": 100
}

POST http://localhost:13000/user/register
content-type: application/json

{
  "email": "a@b",
  "password": "123456"
}

POST http://localhost:13000/user/login
content-type: application/json

{
  "email": "a@a",
  "password": "123456"
}