POST http://localhost:13000/maker/save-settings/device1
content-type: application/json

{
  "online": true,
  "minAmount": 100,
  "maxAmount": 1000,
  "range": 10
}

POST http://localhost:13000/taker/register/device1
content-type: application/json

{
  "lat": "37.797897",
  "lng": "34.850000"
}

POST http://localhost:13000/taker/create-withdrawal/device1
content-type: application/json

{
  "lat": "37.797897",
  "lng": "34.850000"
}
