POST http://localhost:13000/user/update-location
content-type: application/json
Authorization: Bearer demo-user-token

{
  "location": {
    "lat": "37.797897",
    "lng": "39.850000"
  }
}

POST http://localhost:13000/maker/save-settings
content-type: application/json
Authorization: Bearer demo-user-token

{
  "minAmount": 100,
  "maxAmount": 1000,
  "range": 10
}

POST http://localhost:13000/maker/toggle-online
content-type: application/json
Authorization: Bearer demo-user-token

{
  "online": true
}

POST http://localhost:13000/taker/create-withdrawal
content-type: application/json
Authorization: Bearer demo-user-token

{
  "amount": 100
}

POST http://localhost:13000/user/register
content-type: application/json

{
  "email": "a@a",
  "password": "123456"
}

POST http://localhost:13000/user/login
content-type: application/json

{
  "email": "a@a",
  "password": "123456"
}